name: pokemon_app
description: Take Home Test by developing Pokemon App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # networking
  dio: ^5.2.0
  cached_network_image: ^3.2.3
  html: ^0.15.1

  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # model
  json_annotation: ^4.8.0

  #  DI
  get_it: ^7.6.0
  injectable: ^2.1.1

  #UIfvm flutter pub get
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.0
  intl: ^0.17.0
  intl_utils: ^2.8.3
  touchable_opacity: ^1.2.0

  #Storage
  flutter_secure_storage: ^8.1.0
  floor: ^1.4.2
#  sqflite: ^2.3.2

  #Utils
  url_launcher: ^6.1.11
  flutter_screenutil: ^5.7.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # unit test
  mockito: ^5.4.0
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5
  flutter_launcher_icons: ^0.10.0
  json_serializable: ^6.3.1
  bloc_test: ^9.1.3
  floor_generator: ^1.4.2

flutter:  
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true

flutter_icons:
  image_path: "assets/images/pokeapi_ic.png"
  android: true
  ios: true
